### ISSUE TITLE
Inquiry about the results of dram_v distill

### ISSUE THREAD

**Issue by fhdbqr** [yan1365/RVD#1]
Congratulations on your outstanding work! I have a few questions regarding the identification of virus-encoded auxiliary metabolic genes. In the outputs of Dram_v distill, there are some genes originating from the amg_database, so they do not have categories such as "MISC" or "Carbohydrate utilization," among others. How are these handled?

**Comment by yan1365** [comment]
Hi,

Thank you for your interest to my work. Regarding the AMG identification, it relies heavily on manual curations (genomic context of phage genomes and manual annotation/literature search of individual genes). You can check the Supplementary Table 4 to have a general idea about how it is done.  

Best,
Ming

**Comment by fhdbqr** [comment]
Thank you for your response. Your work has been a great inspiration to me.
